#
# BCM56780 40x200g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_1350MHZ
...
---
bcm_device:
    0:
        global:
            uft_mode: 1
            l3_aplm_template: 1
            l2_learn_enable: 1
#            vlan_flooding_l2mc_num_reserved: 0
            pktio_mode: 0
            bcm_tunnel_term_compatible_mode: 1
            l3_alpm_template: 2
            l3_alpm2_bnk_threshold: 100
            l3_enable: 1
            l2_hitbit_enable: 0
...
---
bcm_device:
    0:
        port:
            3:
                dport_map_port: 1
            4:
                dport_map_port: 2
            1:
                dport_map_port: 3
            2:
                dport_map_port: 4
            7:
                dport_map_port: 5
            8:
                dport_map_port: 6
            20:
                dport_map_port: 7
            21:
                dport_map_port: 8
            5:
                dport_map_port: 9
            6:
                dport_map_port: 10
            9:
                dport_map_port: 11
            24:
                dport_map_port: 12
            10:
                dport_map_port: 13
            25:
                dport_map_port: 14
            22:
                dport_map_port: 15
            28:
                dport_map_port: 16
            23:
                dport_map_port: 17
            29:
                dport_map_port: 18
            26:
                dport_map_port: 19
            27:
                dport_map_port: 20
            42:
                dport_map_port: 21
            43:
                dport_map_port: 22
            46:
                dport_map_port: 23
            40:
                dport_map_port: 24
            47:
                dport_map_port: 25
            41:
                dport_map_port: 26
            60:
                dport_map_port: 27
            44:
                dport_map_port: 28
            61:
                dport_map_port: 29
            45:
                dport_map_port: 30
            64:
                dport_map_port: 31
            65:
                dport_map_port: 32
            48:
                dport_map_port: 33
            49:
                dport_map_port: 34
            62:
                dport_map_port: 35
            63:
                dport_map_port: 36
            68:
                dport_map_port: 37
            69:
                dport_map_port: 38
            66:
                dport_map_port: 39
            67:
                dport_map_port: 40
            38:
                dport_map_port: 41
            78:
                dport_map_port: 42
            "*":
                encap_mode: IEEE
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32104567
                TX_LANE_MAP: 0x74653120
                RX_POLARITY_FLIP: 0xdd
                TX_POLARITY_FLIP: 0x77
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x27435160
                TX_LANE_MAP: 0x02137456
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x1
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45670231
                TX_LANE_MAP: 0x32105764
                RX_POLARITY_FLIP: 0x82
                TX_POLARITY_FLIP: 0x25
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64572301
                TX_LANE_MAP: 0x32105764
                RX_POLARITY_FLIP: 0xee
                TX_POLARITY_FLIP: 0x20
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x02315764
                TX_LANE_MAP: 0x12035476
                RX_POLARITY_FLIP: 0x24
                TX_POLARITY_FLIP: 0x25
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23016475
                TX_LANE_MAP: 0x54762013
                RX_POLARITY_FLIP: 0x4d
                TX_POLARITY_FLIP: 0x16
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46571032
                TX_LANE_MAP: 0x76452301
                RX_POLARITY_FLIP: 0x81
                TX_POLARITY_FLIP: 0x96
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x75642301
                TX_LANE_MAP: 0x54761320
                RX_POLARITY_FLIP: 0x84
                TX_POLARITY_FLIP: 0x16
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x07564312
                TX_LANE_MAP: 0x65047231
                RX_POLARITY_FLIP: 0x8b
                TX_POLARITY_FLIP: 0x2b
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01235476
                TX_LANE_MAP: 0x13025746
                RX_POLARITY_FLIP: 0x28
                TX_POLARITY_FLIP: 0x77
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76542031
                TX_LANE_MAP: 0x45670213
                RX_POLARITY_FLIP: 0xdf
                TX_POLARITY_FLIP: 0x52
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x31427056
                TX_LANE_MAP: 0x27136540
                RX_POLARITY_FLIP: 0x75
                TX_POLARITY_FLIP: 0xb5
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01236475
                TX_LANE_MAP: 0x23017465
                RX_POLARITY_FLIP: 0xed
                TX_POLARITY_FLIP: 0x68
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x13204567
                TX_LANE_MAP: 0x10325647
                RX_POLARITY_FLIP: 0x73
                TX_POLARITY_FLIP: 0x52
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x27061435
                TX_LANE_MAP: 0x64752301
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x83
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64570123
                TX_LANE_MAP: 0x64573210
                RX_POLARITY_FLIP: 0xee
                TX_POLARITY_FLIP: 0xf2
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54762301
                TX_LANE_MAP: 0x32105764
                RX_POLARITY_FLIP: 0x7e
                TX_POLARITY_FLIP: 0x75
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45673210
                TX_LANE_MAP: 0x32105764
                RX_POLARITY_FLIP: 0x2b
                TX_POLARITY_FLIP: 0x25
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x51602743
                TX_LANE_MAP: 0x47652301
                RX_POLARITY_FLIP: 0x53
                TX_POLARITY_FLIP: 0x18
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32104567
                TX_LANE_MAP: 0x74652301
                RX_POLARITY_FLIP: 0x7d
                TX_POLARITY_FLIP: 0xb0
            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x3120
                TX_LANE_MAP: 0x3120
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x00
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 9
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 10
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 25
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 28
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 29
            :
                PC_PHYS_PORT_ID: 77
            ?
                PORT_ID: 26
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 27
            :
                PC_PHYS_PORT_ID: 69
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 93
            ?
                PORT_ID: 46
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 47
            :
                PC_PHYS_PORT_ID: 109
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 85
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 44
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 125
            ?
                PORT_ID: 45
            :
                PC_PHYS_PORT_ID: 101
            ?
                PORT_ID: 64
            :
                PC_PHYS_PORT_ID: 141
            ?
                PORT_ID: 65
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 48
            :
                PC_PHYS_PORT_ID: 117
            ?
                PORT_ID: 49
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 133
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 68
            :
                PC_PHYS_PORT_ID: 157
            ?
                PORT_ID: 69
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 66
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 67
            :
                PC_PHYS_PORT_ID: 149
            ?
               # management port
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 78
            :
                PC_PHYS_PORT_ID: 162
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 10],
                          [20, 29],
                          [40, 49],
                          [60, 69]]
            :
                &port_mode_200g
                ENABLE: 1
                SPEED: 200000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [38,     # Management port 0 (Pipe 1)
                          78]     # Management port 1 (Pipe 3)
            :
                &port_mode_10g_xfi
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 0x3fe8
...
---
device:
    0:
        PC_TX_TAPS:
            ?
                PORT_ID: [1,2,3,4,66,67,68,69]
                LANE_INDEX: [0, 1, 2, 3]
            :
                TX_SIG_MODE: PC_SIG_MODE_PAM4
                TX_SIG_MODE_AUTO: 0
                TXFIR_TAP_MODE: PC_TXFIR_PAM4_TAPS_6
                TXFIR_TAP_MODE_AUTO: 0
                TX_PRE_SIGN: 1
                TX_PRE: 12
                TX_PRE_AUTO: 0
                TX_MAIN_SIGN: 0
                TX_MAIN: 136
                TX_MAIN_AUTO: 0
                TX_POST_SIGN: 1
                TX_POST: 12
                TX_POST_AUTO: 0
                TX_PRE2_SIGN: 0
                TX_PRE2: 0
                TX_PRE2_AUTO: 0
                TX_POST2_SIGN: 0
                TX_POST2: 0
                TX_POST2_AUTO: 0
                TX_POST3_SIGN: 0
                TX_POST3: 0
                TX_POST3_AUTO: 0
            ?
                PORT_ID: [5,6,7,8,20,21,62,63,64,65,48,49]
                LANE_INDEX: [0, 1, 2, 3]
            :
                TX_SIG_MODE: PC_SIG_MODE_PAM4
                TX_SIG_MODE_AUTO: 0
                TXFIR_TAP_MODE: PC_TXFIR_PAM4_TAPS_6
                TXFIR_TAP_MODE_AUTO: 0
                TX_PRE_SIGN: 1
                TX_PRE: 8
                TX_PRE_AUTO: 0
                TX_MAIN_SIGN: 0
                TX_MAIN: 116
                TX_MAIN_AUTO: 0
                TX_POST_SIGN: 1
                TX_POST: 4
                TX_POST_AUTO: 0
                TX_PRE2_SIGN: 0
                TX_PRE2: 0
                TX_PRE2_AUTO: 0
                TX_POST2_SIGN: 0
                TX_POST2: 0
                TX_POST2_AUTO: 0
                TX_POST3_SIGN: 0
                TX_POST3: 0
                TX_POST3_AUTO: 0
            ?
                PORT_ID: [9,10,24,25,22,28,23,29,26,27,42,43,46,40,47,41,60,44,61,45]
                LANE_INDEX: [0, 1, 2, 3]
            :
                TX_SIG_MODE: PC_SIG_MODE_PAM4
                TX_SIG_MODE_AUTO: 0
                TXFIR_TAP_MODE: PC_TXFIR_PAM4_TAPS_6
                TXFIR_TAP_MODE_AUTO: 0
                TX_PRE_SIGN: 1
                TX_PRE: 8
                TX_PRE_AUTO: 0
                TX_MAIN_SIGN: 0
                TX_MAIN: 112
                TX_MAIN_AUTO: 0
                TX_POST_SIGN: 0
                TX_POST: 0
                TX_POST_AUTO: 0
                TX_PRE2_SIGN: 0
                TX_PRE2: 0
                TX_PRE2_AUTO: 0
                TX_POST2_SIGN: 0
                TX_POST2: 0
                TX_POST2_AUTO: 0
                TX_POST3_SIGN: 0
                TX_POST3: 0
                TX_POST3_AUTO: 0
...
---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...
